config/routes.rb
Rails.application.routes.draw do
  get "images/ogp"
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root "static_pages#top"
  get '/terms_of_service', to: 'static_pages#terms_of_service', as: 'terms_of_service'
  get '/privacy_policy', to: 'static_pages#privacy_policy', as: 'privacy_policy'

  resources :users, only: %i[new create show]
  resource :user_sessions, only: [:new, :create, :destroy]

  resources :boards, only: %i[index show new create edit update destroy] do
    collection do
      get 'search', to: 'boards#search'
      get :autocomplete
      get 'by_camera_make', to: 'boards#by_camera_make'  
      get :bookmarks
    end
  end

  resources :bookmarks, only: %i[create destroy]

  resources :cameras, only: [:create]
  resource :profile, only: %i[show edit update]

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :password_resets, only: %i[new create edit update]

  get 'camera_make/:make', to: 'boards#by_camera_make', as: :by_camera_make
  get 'camera_model/:model', to: 'boards#by_camera_model', as: :by_camera_model

  get 'cameras/search', to: 'cameras#search'
  get 'boards/search', to: 'boards#search'
  get 'autocomplete', to: 'boards#autocomplete'
  get 'autocomplete', to: 'autocomplete#index'
  post 'add_camera_model', to: 'boards#add_camera_model'

  get 'top', to: 'static_pages#top', as: 'static_pages_top'

  post 'save_camera_model', to: 'camera_models#save'

  post '/oauth/google', to: 'oauths#oauth'
  post 'oauth/google', to: 'oauths#google'
  get '/oauth/google', to: 'oauths#oauth', as: 'google_oauth'
  get '/oauth/callback', to: 'oauths#callback', as: 'google_oauth_callback'
  get '/oauth/callback', to: 'oauths#callback'
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!


  attr_accessor :password_confirmation
  attr_accessor :remember_token

  validates :user_name, presence: { message: 'ユーザー名を入力してください' }

  validates :password, length: { minimum: 3, message: I18n.t('activerecord.errors.models.user.attributes.password.too_short') }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: { message: I18n.t('activerecord.errors.models.user.attributes.password.confirmation') }, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: { message: I18n.t('activerecord.errors.models.user.attributes.password_confirmation.blank') }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: { message: I18n.t('activerecord.errors.models.user.attributes.password_confirmation.mismatch') }, if: -> { password.present? }

  validates :email, presence: true, uniqueness: true
  validates :reset_password_token, uniqueness: true, allow_nil: true

  validates :bio, length: { maximum: 160, message: '自己紹介文は160文字以内で入力してください' }

  has_many :boards, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_boards, through: :bookmarks, source: :board

  has_one_attached :avatar

  has_many :authentications, :dependent => :destroy
  accepts_nested_attributes_for :authentications

  def bookmark(board)
    bookmark_boards << board
  end

  def unbookmark(board)
    bookmark_boards.destroy(board)
  end

  def bookmark?(board)
    bookmark_boards.include?(board)
  end

  def own?(board)
    board.user == self
  end

  def self.new_token 
    SecureRandom.urlsafe_base64
  end

  def self.digest(string) 
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil? 
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def self.from_omniauth(id_token)
    user_info = get_google_user_info(id_token)
  
    user = User.find_by(email: user_info[:email])
    return user if user
  
    password = SecureRandom.hex(10) 
    new_user = User.new(
      email: user_info[:email],
      user_name: user_info[:name],
      password: password,
      password_confirmation: password 
    )
  
    if new_user.save
      return new_user
    else
      Rails.logger.error("User creation failed: #{new_user.errors.full_messages.join(', ')}")
      return nil
    end
  end
  
  private

  def self.get_google_user_info(id_token)
    response = RestClient.get("https://www.googleapis.com/oauth2/v3/tokeninfo?id_token=#{id_token}")
    JSON.parse(response.body).symbolize_keys
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :require_login, only: %i[new create]
  
    def new
      @user = User.new
    end
  
    def create
      @user = User.new(user_params)
      if @user.save
        auto_login(@user)
        redirect_to root_path, success: '登録が完了しました'
      else
        flash.now[:danger] = 'ユーザー登録に失敗しました'
        render :new, status: :unprocessable_entity
      end
    end

    def show
        @user = User.find(params[:id]) 
        @boards = @user.boards.order(created_at: :desc).page(params[:page]).per(30)
    end 
  
    private
  
    def user_params
      params.require(:user).permit(:user_name, :email, :password, :password_confirmation, :avatar_url)
    end
end

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-auto">
        <div class="d-flex justify-content-center align-items-center mb-5">
            <h1 class="text-center" style="font-size: 24px; font-weight: 300;">新 規 登 録</h1>
        </div>
      <%= form_with model: @user, data: { turbo: false } do |f| %>

         <%= render 'shared/error_messages', object: f.object %>
         
        <div class="mb-4 row justify-content-center">
          <div class="col-sm-2">
            <%= f.label :user_name, "ユーザーネーム", class: "form-label", style: "font-size: 17px; font-weight: 300;" %>
          </div>
          <div class="col-sm-7">
            <%= f.text_field :user_name, class: "form-control" %>
          </div>
        </div>
        
        <div class="mb-4 row justify-content-center">
          <div class="col-sm-2">
            <%= f.label :email, "メールアドレス", class: "form-label", style: "font-size: 17px; font-weight: 300;" %>
          </div>
          <div class="col-sm-7">
            <%= f.email_field :email, class: "form-control" %>
          </div>
        </div>
        
        <div class="mb-4 row justify-content-center">
          <div class="col-sm-2">
            <%= f.label :password, "パスワード", class: "form-label", style: "font-size: 17px; font-weight: 300;" %>
          </div>
          <div class="col-sm-7">
            <%= f.password_field :password, class: "form-control" %>
          </div>
        </div>
        
        <div class="mb-4 row justify-content-center">
          <div class="col-sm-2">
            <%= f.label :password_confirmation, "パスワードの確認", class: "form-label", style: "font-size: 15px; font-weight: 300;" %>
          </div>
          <div class="col-sm-7">
            <%= f.password_field :password_confirmation, class: "form-control" %>
          </div>
        </div>
        
        <div class="row mt-5">
          <div class="col text-center mb-4">
            <%= f.submit "登録", class: "btn btn-primary" %>
          </div>
        </div>

        <div class="text-center mb-3">
        <%= link_to 'ログインページへ', login_path, style: 'text-decoration: none; color: #6fa8dc; transition: color 0.3s;' %>
      </div>
            
      <% end %>      
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container pt-3">
  <div class="row">
    <div class="col-md-10 offset-md-1">

      <div class="user-info">
        <div class="d-flex align-items-center">

          <%= image_tag(@user.avatar_url || asset_path('sample.png'), class: 'rounded-circle avatar_size', size: '120x120') %>

          <h1 class="user-name">
            <%= @user.user_name %>

            <% if @user == current_user %>  
              <%= link_to edit_profile_path do %>
                <%= image_tag 'edit.png', alt: 'Edit', size: '20x20', class: 'ml-2' %>
              <% end %>
            <% end %>
          </h1>
        </div>

        <p class="user-bio mt-3 text-center" style="max-width: 600px; max-height: 200px; overflow: hidden; margin-left: auto; margin-right: auto;">
          <%= @user.bio %>
        </p>
      </div>

      <div class="user-posts" style="padding-bottom: 50px; margin-top: -30px;">
        <h2 style="line-height: 1; font-weight: 300; text-align: center; margin-bottom: 40px;">
          <%= "#{@user.user_name}さんの投稿一覧" %>
        </h2>
        <% if @boards.any? %>
        <div class="image-container2 d-flex flex-wrap justify-content-center">
          <% @boards.each do |board| %>
            <div class="image-item2">
              <%= link_to board_path(board) do %>
                <!-- 画像URLを直接表示する -->
                <% if board.board_image_url.present? %>
                <% if board.board_image_url.ends_with?('.jpg', '.jpeg', '.png', '.gif') %>
                  <%= image_tag(board.board_image_url, class: 'img-fluid') %>
                <% elsif board.board_image_url.ends_with?('.mp4', '.webm', '.ogg') %>
                  <%= video_tag(board.board_image_url, controls: true, class: 'img-fluid', style: 'height: 200px; width: auto; max-width: 100%; object-fit: contain; display: block; margin: 0; padding: 0;') %>
                <% end %>
              <% end %>
              <% end %>
            </div>
          <% end %>
        </div>
        <% else %>
          <p style="text-align: center; color: #888; font-size: 18px; margin-top: 100px;">まだ投稿はありません</p>
        <% end %>
        <%= paginate @boards %>
      </div>
    </div>
  </div>
</div>