config/routes.rb
Rails.application.routes.draw do
  get "images/ogp"
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root "static_pages#top"
  get '/terms_of_service', to: 'static_pages#terms_of_service', as: 'terms_of_service'
  get '/privacy_policy', to: 'static_pages#privacy_policy', as: 'privacy_policy'

  resources :users, only: %i[new create show]
  resource :user_sessions, only: [:new, :create, :destroy]

  resources :boards, only: %i[index show new create edit update destroy] do
    collection do
      get 'search', to: 'boards#search'
      get :autocomplete
      get 'by_camera_make', to: 'boards#by_camera_make'  
      get :bookmarks
    end
  end

  resources :bookmarks, only: %i[create destroy]

  resources :cameras, only: [:create]
  resource :profile, only: %i[show edit update]

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :password_resets, only: %i[new create edit update]

  get 'camera_make/:make', to: 'boards#by_camera_make', as: :by_camera_make
  get 'camera_model/:model', to: 'boards#by_camera_model', as: :by_camera_model

  get 'cameras/search', to: 'cameras#search'
  get 'boards/search', to: 'boards#search'
  get 'autocomplete', to: 'boards#autocomplete'
  get 'autocomplete', to: 'autocomplete#index'
  post 'add_camera_model', to: 'boards#add_camera_model'

  get 'top', to: 'static_pages#top', as: 'static_pages_top'

  post 'save_camera_model', to: 'camera_models#save'

  post '/oauth/google', to: 'oauths#oauth'
  post 'oauth/google', to: 'oauths#google'
  get '/oauth/google', to: 'oauths#oauth', as: 'google_oauth'
  get '/oauth/callback', to: 'oauths#callback', as: 'google_oauth_callback'
  get '/oauth/callback', to: 'oauths#callback'
end

app/views/shared/_before_login_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navigation navbar-light bg-light">

    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.jpg" %>
    <% end %>

    <button class='navbar-toggler' data-bs-toggle='collapse' data-bs-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto main-nav align-items-center">
        <li class="nav-item">
          <a class="modal-btn nav-link text-center" href="#modal" style="font-size: 0.8rem; line-height: 1.2;">
            <%= image_tag("note.png", class: "note-icon-class", style: "width: 30px; height: 30px; margin-bottom: -2px;") %>
            <span class="note-icon-text" style="font-size: 0.7rem;">使い方</span>
          </a>
        </li>
        <li class="nav-item">
          <%= link_to login_path, class: "nav-link" do %>
            <%= image_tag("login.png", class: "login-icon-class") %>
            <span class="login-icon-text">ログイン/新規登録</span>
          <% end %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.each do |error| %>
        <% unless error.attribute.to_s == 'camera' %>
          <li><%= error.message %></li>
        <% end %>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>">
      <%= message %>
    </div>
<% end %>

app/views/shared/_footer.html.erb
<footer id="footer" class="footer-bottom footer">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-12">
        <div class="links">
          <a href="<%= terms_of_service_path %>">利用規約</a> |
          <a href="<%= privacy_policy_path %>">プライバシーポリシー</a>
        </div>
      </div>
      <div class="col-sm-6 col-12 text-sm-right">
        <div class="copyright">
          <p>Copyright © 2024 OldCam1700</p>
        </div>
      </div>
    </div>
  </div>
</footer>




app/views/shared/_google_signin_button.html.erb
<html>
  <head>
    <meta name="google-signin-client_id" content="561585853461-5h5kubhcidtgtnaebovacqd5i948vavf.apps.googleusercontent.com">
  </head>
  <body>
    <div id="my-signin2"></div>
    <script>
      function onSuccess(googleUser) {
        var id_token = googleUser.credential;

        fetch('/oauth/google', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            id_token: id_token,
          }),
        })
        .then(response => response.json())
        .then(data => {
          if (data.success) {
            alert(data.message);
            window.location.href = data.redirect_url;
          } else {
            console.error('Login failed:', data.message);
            alert(data.message); 
          }
        })
        .catch(error => {
          console.error('Error:', error);
        });
      }

      function onFailure(error) {
        console.log(error);
      }

      function renderButton() {
        google.accounts.id.initialize({
          client_id: '561585853461-5h5kubhcidtgtnaebovacqd5i948vavf.apps.googleusercontent.com',
          callback: onSuccess,
        });

        google.accounts.id.renderButton(
          document.getElementById('my-signin2'),
          { theme: 'outline', size: 'large' }
        );

        google.accounts.id.prompt();
      }

      window.onload = renderButton;
    </script>
    <script src="https://accounts.google.com/gsi/client" async defer></script>
  </body>
</html>

app/views/shared/_header.html.erb
<header>
  <nav class='navbar navbar-expand-lg navigation navbar-light bg-light'>
    <%= link_to root_path, class: 'navbar-brand' do %>
      <%= image_tag 'logo.jpg' %>
    <% end %>
    <button class='navbar-toggler' data-bs-toggle='collapse' data-bs-target='#navbarSupportedContent'
      aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class='navbar-toggler-icon'></span>
    </button>

    <div class='collapse navbar-collapse' id='navbarSupportedContent'>
      <ul class='navbar-nav ms-auto main-nav align-items-center'>

    
      <li class="nav-item">
        <a class="modal-btn nav-link text-center" href="#modal" style="font-size: 0.8rem; line-height: 1.2;">
          <%= image_tag("note.png", class: "note-icon-class", style: "width: 30px; height: 30px; margin-bottom: -2px;") %>
          <span class="note-icon-text" style="font-size: 0.7rem;">使い方</span>
        </a>
      </li>

        <li class='nav-item'>
        <%= link_to '投稿する', new_board_path, class: 'nav-link' %>
        </li>

        <li class='nav-item dropdown dropdown-slide'>
          <%= link_to '#', class: 'nav-link', data: { bs_toggle: 'dropdown' }, aria: { haspopup: 'true', expanded: 'false' }, id: 'header-profile' do %>
            <%= image_tag(current_user.avatar_url || asset_path('sample.png'), class: 'rounded-circle', width: '40', height: '40') %>
          <% end %>
          <div class='dropdown-menu dropdown-menu-end'>
            <%= link_to 'マイページ', profile_path, class: 'dropdown-item' %>
            <%# = link_to 'いいねした投稿', bookmarks_boards_path, class: 'dropdown-item' #%>
            <%= form_with url: logout_path, method: :delete, class: 'd-inline' do %>
                <button type="submit" class="dropdown-item">ログアウト</button>
            <% end %>
          </div>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_modal.html.erb
<section role="dialog" aria-labelledby="modal-title" class="modal" id="modal">
<a class="modal-overlay" href="#" tabindex="-1"></a>

<div class="modal-content">
  <a title="Close modal" aria-label="Close modal" href="#" class="modal-close">&times; </a>
  <h1 id="modal-title"> OldCam1700へようこそ! </h1>
  <p>
    オールドコンデジで撮ったお気に入りの写真や動画を簡単に投稿できるサービスです。<br>
    写真や動画は1700万画素以下で投稿できます。オールドコンデジならではの独特の味わいを楽しんでください！<br>
    また、カメラの機種やメーカーで写真を検索し、気になるカメラの写りを比較することができます。<br>
  </p>

  <h2>OldCam1700の使い方</h2>
  <p><strong>1. アカウント作成</strong></p>
  <p>
    アプリを利用するには、まずアカウントを作成しましょう<br>
    画面右上の「新規登録」ボタンよりアカウントの作成が可能です。<br>
  </p>

  <p><strong>2. ログイン</strong></p>
  <p>
    すでにアカウントをお持ちの方は、ログインページからメールアドレスとパスワードを入力してログインできます。<br>
    Googleアカウントでのログインも可能です。<br>
  </p>

  <p><strong>3. 投稿する</strong></p>
  <p>
    ログイン後、右上の「投稿する」ボタンから、あなたの投稿を作成できます。<br>
    あなたが撮ったお気に入りの写真や動画を投稿しましょう。<br>
  </p>

  <p><strong>4. 他の投稿を見る</strong></p>
  <p>
    他のユーザーの投稿をチェックするには、ホーム画面をスクロールするだけ。<br>
    素敵な投稿には「いいね！」をすることもできます。<br>
  </p>

  <p><strong>5. 検索する</strong></p>
  <p>
    気になるカメラや投稿を検索するには、画面上部の検索バーを使いましょう。<br>
    カメラの機種やメーカー名を入力することで、関連する写真や動画を簡単に見つけることができます。<br>
  </p>

  <p><strong>6. マイページ</strong></p>
  <p>
    自分の投稿やプロフィールを管理したい場合は、画面右上の「マイページ」からアクセスできます。<br>
    プロフィール画像やユーザーネーム、自己紹介、登録したメールアドレスの変更が可能です。<br>
  </p>

  <p><strong>7. ログアウト</strong></p>
  <p>
    右上の「ログアウト」ボタンでアカウントからログアウトできます。<br>
  </p>

  <p>
    <span style="font-size: 10px; display: inline-block; margin-top: 30px;">
      説明を閉じるには、トップ右上の×ボタンをクリックしてください。
    </span><br>
  </p>
</div>
</section>


<style>
/* モーダルの背景 */
.modal {
  display: none; /* 初期状態は非表示 */
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: rgba(0, 0, 0, 0.5); /* 半透明の背景 */
  justify-content: center;
  align-items: center;
  z-index: 1000;
}

/* モーダルがリンククリック時に表示される */
.modal:target {
  display: flex; /* ターゲットが指定されると表示 */
}

/* モーダル内のコンテンツ */
.modal-content {
  background-color: white;
  padding: 20px;
  border-radius: 5px;
  text-align: center;
  width: 80%;
  max-width: 700px;
  max-height: 80vh; /* モーダルの高さを最大80%に制限 */
  overflow-y: auto; /* 内容が多ければスクロール */
}

.modal-close {
  position: absolute;
  top: 10px;
  right: 10px;
  font-size: 24px;
  color: #000;
  text-decoration: none;
}

.modal-btn {
  color: black;         /* 文字色を黒に設定 */
  text-decoration: none; /* 下線を削除 */
  position: relative;    /* 少し位置を調整するために必要 */
  top: -2px;             /* 上に少し表示させる（数値を調整して好みに合わせてください） */
  font-weight: 325;
}

</style>