config/routes.rb
Rails.application.routes.draw do
  get "images/ogp"
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root "static_pages#top"
  get '/terms_of_service', to: 'static_pages#terms_of_service', as: 'terms_of_service'
  get '/privacy_policy', to: 'static_pages#privacy_policy', as: 'privacy_policy'

  resources :users, only: %i[new create show]
  resource :user_sessions, only: [:new, :create, :destroy]

  resources :boards, only: %i[index show new create edit update destroy] do
    collection do
      get 'search', to: 'boards#search'
      get :autocomplete
      get 'by_camera_make', to: 'boards#by_camera_make'  
      get :bookmarks
    end
  end

  resources :bookmarks, only: %i[create destroy]

  resources :cameras, only: [:create]
  resource :profile, only: %i[show edit update]

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :password_resets, only: %i[new create edit update]

  get 'camera_make/:make', to: 'boards#by_camera_make', as: :by_camera_make
  get 'camera_model/:model', to: 'boards#by_camera_model', as: :by_camera_model

  get 'cameras/search', to: 'cameras#search'
  get 'boards/search', to: 'boards#search'
  get 'autocomplete', to: 'boards#autocomplete'
  get 'autocomplete', to: 'autocomplete#index'
  post 'add_camera_model', to: 'boards#add_camera_model'

  get 'top', to: 'static_pages#top', as: 'static_pages_top'

  post 'save_camera_model', to: 'camera_models#save'

  post '/oauth/google', to: 'oauths#oauth'
  post 'oauth/google', to: 'oauths#google'
  get '/oauth/google', to: 'oauths#oauth', as: 'google_oauth'
  get '/oauth/callback', to: 'oauths#callback', as: 'google_oauth_callback'
  get '/oauth/callback', to: 'oauths#callback'
end

app/models/board.rb
class Board < ApplicationRecord
  validates :title, presence: true, length: { maximum: 255 }
  validates :camera_make, :camera_model, presence: true
  validates :custom_camera_make, presence: true, if: :other_camera_make?
  validates :board_image_url, presence: true
  
  belongs_to :camera
  belongs_to :user

  has_many :bookmarks, dependent: :destroy

  paginates_per 30


  has_one_attached :image
  has_one_attached :video
  has_one_attached :board_image

  def self.ransackable_attributes(auth_object = nil)
    [
      "board_image", "body", "camera_id", "camera_make", "camera_model", 
      "created_at", "id", "image_url", "title", "updated_at", "user_id"
    ]
  end
    
  def self.ransackable_associations(auth_object = nil)
    ["camera", "user"]  
  end

  before_validation :set_camera_id, on: [:create, :update]

  private

  def set_camera_id
    return if camera_make.blank? || camera_model.blank?
  
    camera = Camera.find_or_create_by(make: camera_make, model: camera_model)
    self.camera_id = camera.id
  end

  def other_camera_make?
    camera_make == "その他"
  end

    def custom_camera_make_if_other
    if camera_make == 'その他' && custom_camera_make.blank?
      errors.add(:custom_camera_make, 'カメラのメーカー名を入力してください')
    end
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
    before_action :set_board, only: [:edit, :update, :show, :destroy] 


    def index
      @boards = @user.boards.order(created_at: :desc) 
    end
  
    def new
      @board = Board.new
      @camera_makes = ['Canon', 'Nikon', 'Sony', 'Panasonic']  
    end

    def show
      @board = Board.find(params[:id])

    end
  
    def create
      @board = Board.new(board_params)
      @board.user = current_user 
    
      if @board.board_image.present?
        @board.board_image_url = @board.board_image.url 
      end
    
      if @board.save
        if params[:board][:camera_model] == "その他" && params[:board][:custom_camera_make].present?
          CameraModel.create(name: params[:board][:custom_camera_make])
        end
    
        redirect_to root_path, success: '投稿しました'
      else
        flash.now[:danger] = '投稿に失敗しました'
        render :new, status: :unprocessable_entity
      end
    end
     
    def update
      if @board.update(board_params)
        redirect_to @board, success: '投稿を更新しました'
      else
        flash.now[:danger] = '更新に失敗しました'
        render :edit
      end
    end
  
    def destroy
        @board.destroy
        redirect_to root_path, success: '投稿が削除されました'
    end

    def bookmarks
      @bookmark_boards = current_user.bookmark_boards
                                     .includes(:user)
                                     .order('bookmarks.created_at DESC')
                                     .page(params[:page])
                                     .per(30)
    end

    def like
      @board = Board.find(params[:id])
      @board.increment!(:likes_count) 
    
      respond_to do |format|
        format.html { redirect_to @board }
        format.json { render json: { board_id: @board.id, likes_count: @board.likes_count.to_i } } 
      end
    end
    
def by_camera_make
  @make = params[:make]  
  @custom_make = params[:custom_camera_make]  

  @page_title = if @make == 'その他' && @custom_make.present?
                  @custom_make 
                elsif @make == 'その他'
                  'その他'   
                else
                  @make     
                end

  if @make == 'その他' && @custom_make.present?
    @boards = Board.where('LOWER(camera_make) = ? AND LOWER(custom_camera_make) = ?', @make.downcase, @custom_make.downcase)
                   .order(created_at: :desc)
                   .page(params[:page])
                   .per(30)
  else
    @boards = Board.where('LOWER(camera_make) = ?', @make.downcase)
                   .order(created_at: :desc)
                   .page(params[:page])
                   .per(30)
  end
end

  def by_camera_model
    @model = params[:model]


    @boards = Board.where(camera_model: @model)
                   .order(created_at: :desc)  
                   .page(params[:page])      
                   .per(30)                 
  end

  def edit
    @board = Board.find(params[:id])
    @camera_makes = Camera.distinct.pluck(:make) 
  end

  def search
    query = params.dig(:q, :query_cont) || ""
    if request.format.json?
      @q = Board.ransack(camera_make_or_camera_model_cont: query)
      @boards = @q.result(distinct: true).select(:id, :camera_make, :camera_model)
      render json: @boards.map { |item| { name: "#{item.camera_make} #{item.camera_model}" } }
    else
      @q = Board.ransack(camera_make_or_camera_model_cont: query)
      @boards = @q.result(distinct: true).includes(:user, :camera).order(created_at: :desc).page(params[:page]).per(30)
    end
  end

  def autocomplete
    type = params[:type]
    query = params[:query].downcase 
    fixed_makers = ['Canon', 'Nikon', 'Sony', 'Fujifilm', 'Panasonic', 'Olympus', 'Ricoh', 'Casio', 'Minolta', 'Leica', 'Pentax', 'Kodak', 'Samsung', 'Vivitar', 'Toshiba', 'Yashica', 'Konica', 'Agfa', 'Zenit', 'Voigtländer', 'Polaroid', 'Rollei', 'Minox']    
    make_results = []
    model_results = []
  
    make_results = Board.where('LOWER(camera_make) LIKE ? AND camera_make != ?', 
                                "%#{query}%", "不明")
                         .pluck(:camera_make)
                         .uniq
  
    model_results = Board.where('LOWER(camera_model) LIKE ? AND camera_make != ?', 
                                 "%#{query}%", "不明")
                          .pluck(:camera_model)
                          .uniq

    results = make_results + model_results
    results.concat(fixed_makers.select { |maker| maker.downcase.include?(query) })

    results.uniq!

    render json: results
  end

  def by_custom_camera_make
    @custom_make = params[:custom_camera_make]  
    @boards = Board.where(custom_camera_make: @custom_make)  
  end
  
  private
  
  def set_board
    @board = Board.find_by(id: params[:id])
  end
  
  def board_params
    params.require(:board).permit(:title, :body, :board_image_url, :camera_make, :camera_model, :custom_camera_make)
  end
end
  

app/views/boards/_bookmark.html.erb
<%= link_to bookmarks_path(board_id: board.id), id: "bookmark-button-for-board-#{board.id}", data: { turbo_method: :post } do %>
  <i class="bi bi-heart" style="color: red; font-size: 30px;"></i>
<% end %>

app/views/boards/_bookmark_buttons.html.erb
<div class='ms-auto'>
  <% if current_user.bookmark?(board) %>
    <%= render 'unbookmark', { board: board } %>
  <% else %>
    <%= render 'bookmark', { board: board } %>
  <% end %>
</div>

app/views/boards/_unbookmark.html.erb
<%= link_to bookmark_path(current_user.bookmarks.find_by(board_id: board.id).id), id: "unbookmark-button-for-board-#{board.id}", data: { turbo_method: :delete } do %>
  <i class="bi bi-heart-fill" style="color: red; font-size: 30px;"></i>
<% end %>

app/views/boards/bookmarks.html.erb
<% content_for(:title, "いいねした投稿") %>
<div class="user-posts mt-5" style="padding-bottom: 60px;">
  <h2 style="line-height: 1; font-weight: 300; text-align: center; margin-bottom: -20px;">
    <%= "いいねした投稿" %>
  </h2>
</div>
  <!-- 掲示板一覧 -->
  <% if @bookmark_boards.any? %> 
    <div class="image-container2 d-flex flex-wrap justify-content-center">
      <% @bookmark_boards.each do |board| %>
        <div class="image-item2">
          <%= link_to board_path(board) do %>  
            <% if board.board_image.content_type.starts_with?('image/') %>
              <%= image_tag(board.board_image_url, class: 'img-fluid') %> 
            <% else %>
              <%= video_tag(board.board_image_url, controls: true, class: 'img-fluid', style: 'height: 200px; width: auto; max-width: 100%; object-fit: contain; display: block; margin: 0; padding: 0;') %>  <!-- 動画なら表示 -->
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  <% else %>
    <p style="text-align: center; color: #888; font-size: 18px; margin-top: 100px;">まだいいねした投稿はありません</p>
  <% end %>

  <%= paginate @bookmark_boards %>

app/views/boards/by_camera_make.html.erb
<h2 style="line-height: 1; font-weight: 300; text-align: center; margin-bottom: 60px;">
  "<%= @page_title %>" の投稿一覧
</h2>


<!-- 投稿一覧部分 -->
<div class="image-container2 d-flex flex-wrap justify-content-center">
  <% @boards.each do |board| %>
    <div class="image-item2">
      <%= link_to board_path(board) do %>
        <% if board.board_image_url.present? %>
          <% if board.board_image_url.ends_with?('.jpg', '.jpeg', '.png', '.gif') %>
            <%= image_tag(board.board_image_url, class: 'img-fluid') %>
          <% elsif board.board_image_url.ends_with?('.mp4', '.webm', '.ogg') %>
            <%= video_tag(board.board_image_url, controls: true, class: 'img-fluid', style: 'height: 200px; width: auto; max-width: 100%; object-fit: contain; display: block; margin: 0; padding: 0;') %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

<%= paginate @boards %>


app/views/boards/by_camera_model.html.erb
<h2 style="line-height: 1; font-weight: 300; text-align: center; margin-bottom: 60px;">"<%= @model %>" の投稿一覧</h2>

<div class="image-container2 d-flex flex-wrap justify-content-center">
  <% @boards.each do |board| %>
    <div class="image-item2">
    <%= link_to board_path(board) do %>
      <% if board.board_image_url.present? %>
        <% if board.board_image_url.ends_with?('.jpg', '.jpeg', '.png', '.gif') %>
          <%= image_tag(board.board_image_url, class: 'img-fluid') %>
        <% elsif board.board_image_url.ends_with?('.mp4', '.webm', '.ogg') %>
          <%= video_tag(board.board_image_url, controls: true, class: 'img-fluid', style: 'height: 200px; width: auto; max-width: 100%; object-fit: contain; display: block; margin: 0; padding: 0;') %>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <% end %>
</div>

<%= paginate @boards %>

app/views/boards/by_custom_camera_make.html.erb
<h2 style="line-height: 1; font-weight: 300; text-align: center; margin-bottom: 60px;">"<%= @custom_make %>" の投稿一覧</h2>

<div class="image-container2 d-flex flex-wrap justify-content-center">
  <% @boards.each do |board| %>
    <div class="image-item2">
      <%= link_to board_path(board) do %>
        <%= image_tag board.board_image.url, class: 'img-fluid' %>
      <% end %>
      <p><strong>メーカー:</strong> <%= board.camera_make %></p>
      <p><strong>カスタムメーカー:</strong> <%= board.custom_camera_make.presence || '指定なし' %></p>
    </div>
  <% end %>
</div>

<%= paginate @boards %>

app/views/boards/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h1 class="text-center" style="font-size: 24px; font-weight: 330; margin-bottom: 40px;">投稿の編集</h1>

      <%= form_with model: @board, class: "edit_board" do |f| %>
        
        <%= render 'shared/error_messages', object: f.object %>

        <div class="mb-5 row justify-content-center position-relative">
          <div class="col-sm-2">
            <span class="required-label">必須</span>
            <%= f.label :title, "タ イ ト ル", class: "form-label", style: "font-size: 17px; font-weight: 300;" %>
          </div>
          <div class="col-sm-8">
            <%= f.text_field :title, class: "form-control" %>
          </div>
        </div>

        <div class="mb-5 row justify-content-center position-relative">
          <div class="col-sm-2 col-md-2">
            <span class="required-label">必須</span>
            <%= f.label :camera_make, "カメラの詳細", class: "migi", style: "font-size: 17px; font-weight: 300;" %>
          </div>
          <div class="col-sm-8 col-md-8">
            <div class="row">
              <div class="col-sm-6">
                <%= f.select :camera_make, 
                  [["Canon", "Canon"], ["Casio", "Casio"], ["Kodak", "Kodak"], ["Leica", "Leica"], 
                    ["Minolta", "Minolta"], ["Nikon", "Nikon"], ["Olympus", "Olympus"], ["Panasonic", "Panasonic"], 
                    ["Ricoh", "Ricoh"], ["Sony", "Sony"], ["Yashica", "Yashica"], ["Konica", "Konica"],
                    ["不明", "不明"], ["その他", "その他"]],
                  { prompt: "メーカーを選択してください", selected: @board.camera_make }, 
                  class: "form-control", id: "camera_make_select" %>
              </div>

              <div class="col-sm-6">
                <%= f.text_field :camera_model, class: "form-control", id: "camera_model_input", placeholder: "機種", autocomplete: "off", value: @board.camera_model %>
                <ul id="camera_model_suggestions" class="camera_model_suggestions"></ul>
              </div>
            </div>

            <div id="custom_make_input" class="col-sm-6" style="display: <%= @board.camera_make == 'その他' ? 'block' : 'none' %>; margin-top: 10px;">
              <%= f.text_field :custom_camera_make, placeholder: "メーカー名を入力してください", class: "form-control", id: "custom_camera_make", value: @board.custom_camera_make %>
            </div>
          </div>
        </div>

        <div class="mb-5 row justify-content-center position-relative">
          <div class="col-sm-2">
            <span class="required-label">必須</span>
            <%= f.label :board_image_url, "写 真 ・ 動 画", class: "form-label", style: "font-size: 17px; font-weight: 300;" %>
          </div>
          <div class="col-sm-8">
            <%= f.file_field :board_image_url, class: "form-control", accept: 'image/*,video/*', id: "board_image_url_input" %>
            <div id="error-message" style="color: red;"></div>
            <% if @board.board_image_url.present? %>
              <div id="existing-preview">
                <p>現在の画像:</p>
                <% if @board.board_image_url.ends_with?('.jpg', '.jpeg', '.png', '.gif') %>
                  <%= image_tag @board.board_image_url, class: 'img-fluid' %>
                <% elsif @board.board_image_url.ends_with?('.mp4', '.webm', '.mov') %>
                  <%= video_tag @board.board_image_url, controls: true, class: 'img-fluid', style: 'max-width: 100%; height: auto;' %>
                <% end %>
              </div>
            <% end %>

            <div id="preview"></div>
          </div>
        </div>

        <div class="mb-5 row justify-content-center">
          <div class="col-sm-2">
            <%= f.label :body, "感 想", class: "form-label", style: "font-size: 17px; font-weight: 300;" %>
          </div>
          <div class="col-sm-8">
            <%= f.text_area :body, class: "form-control", rows: "4" %>
          </div>
        </div>

        <div class="row mt-5">
          <div class="col text-center mb-4">
            <%= f.submit "更新", class: "btn btn-primary" %>
          </div>
        </div>

      <% end %>      
    </div>
  </div>
</div>

<script>
document.addEventListener("DOMContentLoaded", function () {
  const cameraMakeSelect = document.getElementById('camera_make_select');
  const customMakeInput = document.getElementById('custom_make_input');

  cameraMakeSelect.addEventListener('change', function() {
    customMakeInput.style.display = cameraMakeSelect.value === 'その他' ? 'block' : 'none';
  });

  if (cameraMakeSelect.value === 'その他') {
    customMakeInput.style.display = 'block';
  }

  const fileInput = document.getElementById("board_image_url");
  const previewContainer = document.getElementById("preview");
  const maxResolution = 17000000; 

  fileInput.addEventListener("change", function (event) {
    const files = event.target.files;
    previewContainer.innerHTML = ""; 

    if (files.length > 0) {
      const file = files[0];
      const reader = new FileReader();
      
      reader.onload = function (e) {
        const fileUrl = e.target.result;
        const img = new Image();

        img.onload = function () {
          const resolution = img.width * img.height;
          
          if (resolution > maxResolution) {
            alert("画像の解像度が1700万画素を超えています。別の画像を選択してください。");
            fileInput.value = ""; 
            previewContainer.innerHTML = ""; 
          } else {
            // 解像度が問題なければプレビューを表示
            const previewElement = document.createElement("img");
            previewElement.src = fileUrl;
            previewElement.classList.add("img-fluid");
            previewContainer.appendChild(previewElement); 
          }
        };

        img.src = fileUrl;
      };

      reader.readAsDataURL(file); 
    }
  });

  const cameraModels = [
    'T4', 'DiMAGE X1', 'DiMAGE 7i', 'XA', 'GR1v', 'S95', 'P7000', 'DMC-LX100', 'Stylus 1', 'GR Digital IV',
    'EX-ZR1000', 'EX-S1', 'A620', 'DiMAGE Xt', 'DSC-T10', 'A590 IS', 'DSC-W70', 'DiMAGE 5', 'SD700 IS', 'DSC-T50',
    '5900', 'G5', '5700', 'DiMAGE A1', 'S230', 'DiMAGE Z3', 'G6', 'DiMAGE Z1', 'SD400', 'DSC-T1', 'A520',
    '8800', 'DiMAGE Z5', 'S3 IS', 'DSC-W50', 'A75', '7900', 'A550', 'DiMAGE 7', 'FinePix F30', 'FZ55', 'PowerShot G7',
    'Coolpix P500', 'Cyber-shot DSC-H5'
  ];

  const sortedCameraModels = cameraModels.sort();

  document.getElementById('camera_model_input').addEventListener('input', function(event) {
    const inputValue = event.target.value.toLowerCase();
    const suggestionsList = document.getElementById('camera_model_suggestions');
    suggestionsList.innerHTML = ''; 
    if (inputValue) {
      const filteredModels = sortedCameraModels.filter(model => model.toLowerCase().includes(inputValue));

      filteredModels.forEach(model => {
        const listItem = document.createElement('li');
        listItem.textContent = model;
        listItem.classList.add('suggestion-item');
        listItem.addEventListener('click', function() {
          document.getElementById('camera_model_input').value = model;
          suggestionsList.innerHTML = ''; 
        });
        suggestionsList.appendChild(listItem);
      });

      const unknownOption = document.createElement('li');
      unknownOption.textContent = '不明';
      unknownOption.classList.add('suggestion-item');
      unknownOption.addEventListener('click', function() {
        document.getElementById('camera_model_input').value = '不明';
      });
      suggestionsList.appendChild(unknownOption);
    }
  });

  document.getElementById('camera_model_input').addEventListener('focus', function() {
    const suggestionsList = document.getElementById('camera_model_suggestions');
    const unknownOption = document.createElement('li');
    unknownOption.textContent = '不明';

    if (![...suggestionsList.children].some(child => child.textContent === '不明')) {
      unknownOption.classList.add('suggestion-item');
      unknownOption.addEventListener('click', function() {
        document.getElementById('camera_model_input').value = '不明';
      });
      suggestionsList.appendChild(unknownOption);
    }
  });
});

</script>

app/views/boards/search.html.erb
<div class="user-posts mt-5">
  <h2 style="line-height: 1; font-weight: 300; text-align: center; margin-bottom: 40px;">
    <%= "#{params.dig(:q, :query_cont)} の検索結果" if params.dig(:q, :query_cont).present? %>
    <%= "検索結果" unless params.dig(:q, :query_cont).present? %>
  </h2>

  <div class="text-center">
    <% if @boards.total_count > 0 %>
      <p>検索結果: <%= @boards.total_count %>件</p>
    <% end %>
  </div>


  <div class="image-container2 d-flex flex-wrap justify-content-center">
  <% @boards.each do |board| %>
    <div class="image-item2">
      <%= link_to board_path(board) do %>
        <% if board.board_image_url.present? %>
          <% if board.board_image_url.ends_with?('.jpg', '.jpeg', '.png', '.gif') %>
            <%= image_tag(board.board_image_url, class: 'img-fluid') %>
          <% elsif board.board_image_url.ends_with?('.mp4', '.webm', '.ogg') %>
            <%= video_tag(board.board_image_url, controls: true, class: 'img-fluid', style: 'height: 200px; width: auto; max-width: 100%; object-fit: contain; display: block; margin: 0; padding: 0;') %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

  <%= paginate @boards %>

  <% if @boards.blank? %> 
    <div class="text-center" style="margin-top: 100px;">
      <p>該当する投稿はありません。</p>
    </div>
  <% end %>
</div>

app/views/boards/show.html.erb
<% show_meta_tags(@board) %>

<div class="container pt-5">
  <div class="row mb-3">
    <div class="col-lg-8 offset-lg-2">
      <article class="card">
        <!-- タイトル -->
        <div class="card-body">
          <h2 class="board-title"><%= @board.title %></h2>

          <% if @board.user == current_user %>
            <div class="action-icons">
              <%= link_to edit_board_path(@board) do %>
                <%= image_tag 'edit.png', alt: 'Edit', class: 'action-icon' %>
              <% end %>

              <%= form_with(model: @board, method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'delete-form') do |form| %>
                <button type="submit" class="btn btn-danger delete-button">
                    <%= image_tag('destroy.png', alt: '削除', class: 'delete-icon') %>
                    この投稿を削除する
                </button>
              <% end %>
            </div>
          <% end %>
        </div>

          <div class="post-info2">
            <div class="camera-info d-flex align-items-center">
              <%= image_tag 'camera.png', alt: 'Camera', class: 'camera-icon' %>
              <p style="margin-top: -5px;">
                <% if @board.camera_make == 'その他' %>
                  <%= link_to @board.custom_camera_make, by_camera_make_path(make: @board.camera_make, custom_camera_make: @board.custom_camera_make) %> /
                <% else %>
                  <%= link_to @board.camera_make, by_camera_make_path(make: @board.camera_make) %> /
                <% end %>
                <%= link_to @board.camera_model, by_camera_model_path(model: @board.camera_model) %>
              </p>
            </div>

            <div class="user-info">
              <p>投稿主: <%= link_to @board.user.user_name, user_path(@board.user) %></p>
              <p>投稿日: <%= l @board.created_at, format: :short %></p>
            </div>
          </div>

          <div class="board-media">
          <% if @board.board_image_url.present? %>
            <% if @board.board_image_url.ends_with?('.jpg', '.jpeg', '.png', '.gif') %>
              <img src="<%= @board.board_image_url %>" style="max-width: 100%; height: auto;">
            <% elsif @board.board_image_url.ends_with?('.mp4', '.webm', '.ogg') %>
              <%= video_tag(@board.board_image_url, controls: true, class: 'video-fluid', style: 'max-width: 100%; height: auto; object-fit: contain; display: block; margin: 0 auto;') %>
            <% end %>
          <% end %>
        </div>
        
        <div class="button-container" style="display: flex; justify-content: space-between; align-items: center;">
          <div class="share-buttons" style="<%= 'margin-top: 5px;' if current_user.own?(@board) %>">
            <a href="https://twitter.com/share?url=<%= request.original_url %>&text=<%= @board.title %>" target="_blank" class="twitter-share-button">Tweet</a>
          </div>
      
          <%= javascript_include_tag "https://platform.twitter.com/widgets.js" %>

          <%# <!-- ブックマークボタンをコメントアウト --> %>
      
          <%# unless current_user.own?(@board) %>
            <%# <!-- 投稿した本人以外にブックマークボタンを表示 --> %>
            <%# <%= render 'bookmark_buttons', { board: @board } %> 
          <%# end %>
        </div>

          <% if @board.body.present? %>
            <div class="board-body mt-4">
              <h4>感想</h4>
              <p><%= simple_format(@board.body) %></p>
            </div>
          <% end %>

        <div class="button-container mt-5">
          <%= link_to '戻る', request.referer || root_path, class: "back_button" %>
        </div>
        
      </article>
    </div>
  </div>
</div>