config/routes.rb
Rails.application.routes.draw do
  get "images/ogp"
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root "static_pages#top"
  get '/terms_of_service', to: 'static_pages#terms_of_service', as: 'terms_of_service'
  get '/privacy_policy', to: 'static_pages#privacy_policy', as: 'privacy_policy'

  resources :users, only: %i[new create show]
  resource :user_sessions, only: [:new, :create, :destroy]

  resources :boards, only: %i[index show new create edit update destroy] do
    collection do
      get 'search', to: 'boards#search'
      get :autocomplete
      get 'by_camera_make', to: 'boards#by_camera_make'  
      get :bookmarks
    end
  end

  resources :bookmarks, only: %i[create destroy]

  resources :cameras, only: [:create]
  resource :profile, only: %i[show edit update]

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :password_resets, only: %i[new create edit update]

  get 'camera_make/:make', to: 'boards#by_camera_make', as: :by_camera_make
  get 'camera_model/:model', to: 'boards#by_camera_model', as: :by_camera_model

  get 'cameras/search', to: 'cameras#search'
  get 'boards/search', to: 'boards#search'
  get 'autocomplete', to: 'boards#autocomplete'
  get 'autocomplete', to: 'autocomplete#index'
  post 'add_camera_model', to: 'boards#add_camera_model'

  get 'top', to: 'static_pages#top', as: 'static_pages_top'

  post 'save_camera_model', to: 'camera_models#save'

  post '/oauth/google', to: 'oauths#oauth'
  post 'oauth/google', to: 'oauths#google'
  get '/oauth/google', to: 'oauths#oauth', as: 'google_oauth'
  get '/oauth/callback', to: 'oauths#callback', as: 'google_oauth_callback'
  get '/oauth/callback', to: 'oauths#callback'
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
    include UserSessionsHelper
    skip_before_action :require_login, only: %i[new create]
  
    def new
      @user = User.new
    end
  
    def create
      @user = login(params[:email], params[:password]) 

      if @user
        if params[:remember_me] == '1'
          remember(@user)
        else
          forget(@user)
        end
        redirect_to root_path, success: 'ログインしました'
      else
        @user = User.new(email: params[:email]) 
        @user.errors.add(:base, 'メールアドレスまたはパスワードが無効です。') 
        flash.now[:danger] = 'ログインに失敗しました'
        render :new, status: :unprocessable_entity
      end
    end
     
    def destroy
      log_out if logged_in?
      redirect_to root_path, status: :see_other, success: 'ログアウトしました'
    end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
    def remember(user)
        user.remember 
        cookies.permanent.signed[:user_id] = user.id 
        cookies.permanent[:remember_token] = user.remember_token 
    end

    def current_user
        if (user_id = session[:user_id])
          @current_user ||= User.find_by(id: user_id)
        elsif (user_id = cookies.signed[:user_id])
          user = User.find_by(id: user_id)
          if user && user.authenticated?(cookies[:remember_token])
            log_in user
            @current_user = user
          end
        end
      end

    def forget(user)
        user.forget 
        cookies.delete(:user_id) 
        cookies.delete(:remember_token) 
    end

    def log_out
        forget(current_user) 
        session.delete(:user_id)
        @current_user = nil
    end  
end

app/views/user_sessions/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-auto">
        <div class="d-flex justify-content-center align-items-center mb-5">
            <h1 class="text-center" style="font-size: 24px; font-weight: 300; flex-grow: 1;">ロ グ イ ン</h1>
        </div>

      <%= form_with(url: user_sessions_path, method: :post) do |f| %>

         <%= render 'shared/error_messages', object: @user %>

        <div class="mb-4 row justify-content-center">
          <div class="col-sm-2">
            <%= f.label :email, "メールアドレス", class: "form-label", style: "font-size: 17px; font-weight: 300;" %>
          </div>
          <div class="col-sm-7">
            <%= f.email_field :email, class: "form-control" %>
          </div>
        </div>
        <div class="mb-4 row justify-content-center">
          <div class="col-sm-2">
            <%= f.label :password, "パスワード", class: "form-label", style: "font-size: 17px; font-weight: 300;"%>
          </div>
          <div class="col-sm-7">
            <%= f.password_field :password, class: "form-control" %>
          </div>
        </div>

        <div class="mb-3 row justify-content-center">
          <div class="col-auto">
            <%= f.label :remember_me do %>
              <%= f.check_box :remember_me, {}, '1', '0' %>
                <span style="font-weight: 300;">ログイン情報を保存する</span>
            <% end %>
          </div>
        </div>

        <div class="row mt-5">
            <div class="col text-center mb-4">
                <%= f.submit "ログイン", class: "btn btn-primary" %>
            </div>
        </div>
      <% end %>

      <div class="d-flex justify-content-center ">
        <div class="text-center mb-3">
          <%= render 'shared/google_signin_button' %>
        </div>
      </div>

      <div class="text-center mb-3">
        <%= link_to '新規登録はこちら', new_user_path, style: 'text-decoration: none; color: #6fa8dc; transition: color 0.3s;' %>
      </div>

      <div class="text-center mb-3">
        <%= link_to 'パスワードをお忘れの方はこちら', new_password_reset_path, class: 'color-link' %>
      </div>
    </div>
  </div>
</div>